### ISSUE TITLE
Transcript level analysis

### ISSUE THREAD

**Issue by trigaten** [trigaten/FedNLP#12]
For each speaker in each meeting, take all of their sentences and give each one a score, then report by sentence scores and averages.

**Comment by DenisPeskoff** [comment]
I think we want to know what the GPT prediction is for a given speaker.  AKA .5 or 0.  Not the average for each sentence they've said.

**Comment by trigaten** [comment]
Closing in favor of https://github.com/trigaten/FedNLP/issues/10

**Comment by trigaten** [comment]
Closing in favor of https://github.com/trigaten/FedNLP/issues/7
