### ISSUE TITLE
Prioritization

### ISSUE THREAD

**Issue by trigaten** [trigaten/FedNLP#14]
1.X
2.Y
3.Z

**Comment by DenisPeskoff** [comment]
First is by far highest priority but all are expected.  Please ask for help if you need preprocessing, etc.  

1.  I've created the data for this so you just have to run it https://github.com/trigaten/FedNLP/issues/7  We need a generated SPEAKER: -1 to 1 prediction for all the transcripts
2. https://github.com/trigaten/FedNLP/issues/15  run all transcripts identical to how we did the first statement run (all -> single prediction)
3. https://github.com/trigaten/FedNLP/issues/16 run all minutes identical to how we did the first statement run (all -> single prediction)

We may want to do some follow up simple experiments but we won't know that till we have results for above.
I'm assuming this is staying under $1k but if not please escalate.
