### ISSUE TITLE
Run all transcript data

### ISSUE THREAD

**Issue by DenisPeskoff** [trigaten/FedNLP#15]
In addition to the by-speaker version of the transcript (https://github.com/trigaten/FedNLP/issues/7), If the cost is <$200,

run all the transcript data the same way as the statements
https://github.com/trigaten/FedNLP/blob/main/data/transcripts.csv

INPUT ENTIRE transcript -> OUTPUT single -1 to 1 prediction.

**Comment by trigaten** [comment]
[out.txt](https://github.com/trigaten/FedNLP/files/11827265/out.txt)

Done-note that this was with last 8K tokens per person.
