### ISSUE TITLE
Few-shot examples

### ISSUE THREAD

**Issue by DenisPeskoff** [trigaten/FedNLP#17]
We need 3-5 good examples of speaker -> [-1, -.5, 0, 1] prediction.

I did a quick attempt but need somebody to verify my labels are accurate.  I'm confident of hawk vs dove but not confident of boundary between .5 and 1

[Tarullo_-1_dove.txt](https://github.com/trigaten/FedNLP/files/11814488/Tarullo_-1_dove.txt)
[Mester_.5_Hawk.txt](https://github.com/trigaten/FedNLP/files/11814489/Mester_.5_Hawk.txt)
[George_1_hawk.txt](https://github.com/trigaten/FedNLP/files/11814490/George_1_hawk.txt)

**Comment by bjw6** [comment]
@DenisPeskov I would agree with all of these. The second one was the trickiest for sure but the labels seem appropriate.
