### ISSUE TITLE
scoring select sentences

### ISSUE THREAD

**Issue by avisokay** [trigaten/FedNLP#20]
@trigaten could you please run each of these sentences to get a score on the hawk dove scale?
[figure_1_examples.csv](https://github.com/trigaten/FedNLP/files/11850414/figure_1_examples.csv)

**Comment by trigaten** [comment]
[codings.txt](https://github.com/trigaten/FedNLP/files/11850783/codings.txt)

Done, but I don't like these results. The prompt consistent even when order of possible labels changes, so I think the prompt may need larger restructuring.

**Comment by avisokay** [comment]
Thanks. I think this is good enough for what we are trying to illustrate.
