### ISSUE TITLE
Run 4 sentences (used for our figure) through GPT

### ISSUE THREAD

**Issue by DenisPeskoff** [trigaten/FedNLP#29]
Run each one as a separate sentence prediction:

1. “The gradual increase in core inflation over the past year is a concern to me.”
2. “I do not believe that there is a very great risk of an unmanageable outbreak of inflation during the relevant policy horizon.”
3. “I think we should not slow our pace of easing moves at this meeting.”

(this one is a statement but don't think that changes anything)
4.“The Committee continues to believe that against the background of its long-run goals of price stability and sustainable economic growth and of the information currently available, the risks are weighted mainly toward conditions that may generate economic weakness in the foreseeable future.”

**Comment by trigaten** [comment]
Here are the scores:
- 0.5
- 0
- -1
- -1


With this prompt:
```
prompt_template = """
<statement>
INPUT
</statement>
<labels>
Dovish: Strongly expresses a belief that the economy may be
growing too slowly and may need stimulus through mon-
etary policy.
Mostly dovish: Overall message expresses a belief that the economy may
be growing too slowly and may need stimulus through
monetary policy.
Neutral: Expresses neither a hawkish nor dovish view and is
mostly objective.
Mostly hawkish: Overall message expresses a belief that the economy is
growing too quickly and may need to be slowed down
through monetary policy.
Hawkish: Strongly expresses a belief that the economy is growing
too quickly and may need to be slowed down through monetary policy.
</labels>
Which label best applies applies to the statement (Dovish, Mostly Dovish, Neutral, Mostly Hawkish, Hawkish)?
"""
```
