### ISSUE TITLE
Re-Run statements with few-shot

### ISSUE THREAD

**Issue by DenisPeskoff** [trigaten/FedNLP#30]
Adam will provide 10 examples in json (text:prediction).  Re-run all statements (double check with Adam but I think it should be ENTIRE statement, not by sentence).

**Comment by avisokay** [comment]
[fednlp_fewshot.csv](https://github.com/trigaten/FedNLP/files/13035723/fednlp_fewshot.csv)
[fednlp_fewshot.json](https://github.com/trigaten/FedNLP/files/13035727/fednlp_fewshot.json)

**Comment by trigaten** [comment]
Following Adam's exemplars, I did it by sentence.
