### ISSUE TITLE
Task 5: Plot Sentence-Level Results

### ISSUE THREAD

**Issue by avisokay** [trigaten/FedNLP#6]
[@Benjamin Wachspress](https://fednlpworkspace.slack.com/team/U05CL5YPEKC) could you please plot the sentence-level results for us? 

In the results folder, it is [this](https://github.com/trigaten/FedNLP/blob/main/results/statement_sentence_avg.csv) file.

line plot
date on the x-axis
hawk/dove score on the y-axis
make sure y-axis label indicates which is hawkish and which is dovish. 

Thanks!

**Comment by bjw6** [comment]
@avisokay please see the results folder for this visual, and let me know if you need anything else

**Comment by avisokay** [comment]
This looks great! The only thing I would change for now is swap where you have the hawk/dove labels on the y-axis so that they correspond to the respective +/-

**Comment by DenisPeskoff** [comment]
we need to be able to compare both results (at sentence and holistic) so plotting both is the next step.

Set the y-axis to [-1, -.5, 0, .5, 1]

Blow up font in everything so it's more readable (and probably rotate x axis labels (2008) more so they fit.

Is a line graph appropriate here @avisokay ?  Are the dates continuous  or distinct?  It does seem to not be independent.  

And the final goal of this will be to include: DEFINITELY the gold label (what you will do with annotation).  And maybe a 4th plot of transcript level.  So thinking about how to compare the data meaningfully.

**Comment by bjw6** [comment]
Here is an adapted version (in [results](https://github.com/trigaten/FedNLP/tree/main/results)), I am going to try to put it into Tableau to make it look nicer but let me know if there are any other glaring issues.

**Comment by bjw6** [comment]
Here is the most updated and [pretty version. ](https://github.com/trigaten/FedNLP/blob/main/results/GPT_Sentiment_Visualization_Tableau.png)
