### ISSUE TITLE
Task 6: Speaker Level Transcript

### ISSUE THREAD

**Issue by avisokay** [trigaten/FedNLP#7]
[@sanderschulhoff](https://fednlpworkspace.slack.com/team/U05CL5YPEKC) Next step is to process the transcripts. The main difference from the statements is we need to produce a hawk/dove score **for each speaker, for each meeting**.   So the first new task is, for each speaker, create a list of all of their sentences. We will then iterate and score those speaker sentences. 

For each transcript from 1994-2016:
     Get all sentences for each speaker:
          For each sentence by speaker:
               Measure each sentence on scale of -1, -0.5, 0, 0.5, 1 (according to Category definitions from above)
          Record average measurement for each speaker
     Return average measurement for each transcript

For example output: {19940204: {greenspan:0.46, yellen:-0.25, geitner:0.65, ... , avg:0.26},
{19940204: {greenspan:0.1, yellen:-0.38, geitner:0.45, ... , avg:-0.15}, etc}

**Comment by trigaten** [comment]
No longer relevant
