### ISSUE TITLE
Task 7: finalizing figure

### ISSUE THREAD

**Issue by DenisPeskoff** [trigaten/FedNLP#8]
We need a beautiful figure to put either in the top right of the second column on the first page that summarizes our task.

Or one on the top of the second page (spanning the entire width).  

(Or likely both, with one explaining the task, and one presenting the results)

**Comment by avisokay** [comment]
TR - "The gradual increase in core inflation over the past year is a concern to me." Human score: 1, GPT-4 score: 0.5

TR - "I do not believe that there is a very great risk of an unmanageable outbreak of inflation during the relevant policy horizon." Human score: -0.5, GPT-4 score: -0.5

TR - "I think we should not slow our pace of easing moves at this meeting." Human score: -1, GPT-4 score: -0.5

ST - "The Committee continues to believe that against the background of its long-run goals of price stability and sustainable economic growth and of the information currently available, the risks are weighted mainly toward conditions that may generate economic weakness in the foreseeable future." Human score: -1, GPT-4 score: -0.5
